#!/usr/bin/env bash

timing="$(basename "$0")"
hooks="$(git rev-parse --git-dir)/hooks/installed/$timing"
cwd="$(pwd)"

if [ -z "$hooks" ]; then
  exit 0
fi

for hook in `ls $hooks`
do
  cd "$cwd"
  ./$hooks/$hook "$@"
  [ "$?" -ne 0 ] && exit 1
done
